Models/Employee.cs
using System.ComponentModel.DataAnnotations;

namespace crud.Models
{
    public class Employee
    {
        [Display(Name= "ID")]
        public int Id { get; set; }
        [DataType("varchar")]
        [MaxLength(50)]
        [Required]
        [Display(Name = "Name")]
        public string Name { get; set; } = null!;
        [DataType(DataType.EmailAddress)]
        [MaxLength(50)]
        [Required]
        [Display(Name = "Email")]
        public string Email { get; set; } = null!;
        [DataType(DataType.Password)]
        [MaxLength(50)]
        [Required]
        [Display(Name = "Password")]
        public string Password { get; set; } = null!;
    }
}

Models/ErrorViewModel.cs
namespace crud.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/User.cs
using System.ComponentModel.DataAnnotations;

namespace crud.Models
{
    public class User
    {
        [Key]
        [Display(Name = "id")]
        public Guid Id { get; set; }
        [Display(Name="name")]
        public string? Name { get; set; }
        [DataType(DataType.Password)]
        [Display(Name = "password")]
        public string? Password { get; set; }
        [Display (Name = "action")]
        public bool IsActive { get; set; }
        [Display(Name="create")]
        public DateTime CreatedAt { get; set; }
    }
}

Controllers/EmployeesController.cs
using crud.Data;
using crud.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace crud.Controllers
{
    public class EmployeesController : Controller
    {
        private readonly appDbContext _context;

        public EmployeesController(appDbContext context)
        {
            _context = context;
        }

        public IActionResult Index()
        {
        //    Employee employee = new Employee()
        //    {
        //        Name = "ahmad",
        //        Email = "ahmad@gmail.com",
        //        Password = "ahmad123"
        //    };
        //    context.Employees.Add(employee);
        //    context.SaveChanges();
        var employees = _context.Employees.AsNoTracking().ToList();
            foreach (var employee in employees)
            {
                Console.WriteLine(employee.Name);
            }

            return View(employees);
        }
        [HttpGet]
        public IActionResult create() 
        { 
            return View(); 
        }
        [HttpPost]
        public IActionResult create(Employee emp)
        {
            _context.Employees.Add(emp);
            _context.SaveChanges();
            return RedirectToAction(nameof(Index));
        }
        public IActionResult delete(int id)
        {
            var emp = _context.Employees.Find(id);
            _context.Employees.Remove(emp);
            _context.SaveChanges();
            return RedirectToAction(nameof(Index));
        }
        public IActionResult update(int id)
        {
            var emp=_context.Employees.Find(id);
            return View(emp);
        }
        public IActionResult edit(Employee emp)
        {
            var employee = _context.Employees.Find(emp.Id);
            employee.Name = emp.Name;
            employee.Email = emp.Email;
            if (emp.Password is not null)
            {
                employee.Password = emp.Password;
            }
           
            _context.SaveChanges();
            return RedirectToAction(nameof(Index));
        }
    }
}

Controllers/HomeController.cs
using crud.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace crud.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/UsersController.cs
using crud.Data;
using crud.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.VisualStudio.Web.CodeGenerators.Mvc.Templates.BlazorIdentity.Pages;

namespace crud.Controllers
{ 
    public class UsersController : Controller
    {
        private readonly appDbContext context;

        public UsersController(appDbContext context)
        {
            this.context = context;
        }
        public IActionResult Register()
        {
            return View();
        }
        public IActionResult Login()
        {
            return View();
        }
        public IActionResult add(User model)
        {
            var user = context.Users.Add(model);
            context.SaveChanges();

            return RedirectToAction(nameof(Login));
        }
        
        public IActionResult check(User model)
        {
            var user=context.Users.Where(user=>user.Name == model.Name && user.Password == model.Password);
            if(user.Any())
            {
                return RedirectToAction(nameof(read));
            }
            ViewBag.Error = "invald username or password";
            return RedirectToAction(nameof(Login));
        }
        public IActionResult read()
        {
            var user =context.Users.Where(user=>user.IsActive==false).ToList();
            return View(user);
        }
        public IActionResult changeIsActive(Guid id)
        {
            var user = context.Users.Find(id);
            user.IsActive = true;
            context.SaveChanges();
            return RedirectToAction(nameof(read));
        }
    }
}

Views/Employees/Index.cshtml
@model IEnumerable<Employee>
@{
    ViewData["Title"] = "Index";
}

<a href="/employees/create" class="btn btn-success"> New</a>
<table class="table">
    <thead>
        <tr>
            <td>
                @Html.DisplayNameFor(model=>model.Id)
            </td>
            <td>
                @Html.DisplayNameFor(model => model.Name)
            </td>
            <td>
                @Html.DisplayNameFor(model => model.Email)
            </td>
            <td>
                @Html.DisplayNameFor(model => model.Password)
            </td>
            <td>
                Action
            </td>
        </tr>
    </thead>
    <tbody>
        @{
           foreach(var item in Model)
            {
                <tr>
                    <td>
                        @item.Id
                    </td>
                    <td>
                        @item.Name
                    </td>
                    <td>
                        @item.Email
                    </td>
                    <td>
                        @item.Password
                    </td>
                    <td>
                        <a asp-controller="employees" asp-action="update" asp-route-id="@item.Id">update</a>
                       <a asp-controller="employees" asp-action="delete" asp-route-id="@item.Id">Delete</a>
                    </td>
                </tr>

                }
          }
    </tbody>
</table>

Views/Employees/create.cshtml
@model Employee
@{
    ViewData["Title"] = "create";
}

<h1>Create Employee</h1>
<form asp-controller="Employees" asp-action="create" class="my-3">
    <div class="my-3">
            <label asp-for="Name"></label>
        <input asp-for="Name"  class="form-control"/>
    </div>
    <div class="my-3">
        <label asp-for="Email"></label>
        <input asp-for="Email" class="form-control" />
    </div>
    <div class="my-3">
        <label asp-for="Password"></label>
        <input asp-for="Password" class="form-control" b/>
    </div>
   <button type="submit" class="btn btn-primary">Add</button>
</form>

Views/Employees/update.cshtml
@model Employee
@{
    ViewData["Title"] = "create";
}

<h1>Update Employee</h1>
<form asp-controller="Employees" asp-action="edit" class="my-3">
    @Html.HiddenFor(Model=>Model.Id);
    <div class="my-3">
        <label asp-for="Name"></label>
        <input asp-for="Name" class="form-control" />
    </div>
    <div class="my-3">
        <label asp-for="Email"></label>
        <input asp-for="Email" class="form-control" />
    </div>
    
    <button type="submit" class="btn btn-primary">Update</button>
</form>

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - crud</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/crud.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">crud</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="employees" asp-action="index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="employees" asp-action="create">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - crud - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/Users/Login.cshtml
@model User
@{
    ViewData["Title"] = "Login";
}

<form asp-controller="users" asp-action="check" class="my-3">

    <div class="my-3">
        <label asp-for="@Model.Name"></label>
        <input asp-for="@Model.Name" class="form-control" />
    </div>
    <div class="my-3">
        <label asp-for="@Model.Password"></label>
        <input asp-for="@Model.Password" class="form-control" />
    </div>
    <button type="submit" class="btn btn-outline-success">login</button>
</form>
<div class="text-danger">@ViewBag.Error</div>

Views/Users/Register.cshtml
@model User
@{
    ViewData["Title"] = "Register";
}

<form asp-controller="users" asp-action="add" class="my-3">
    <div class="my-3">
        <label asp-for="@Model.Name"></label>
        <input asp-for="@Model.Name" class="form-control"/>
    </div>
    <div class="my-3">
        <label asp-for="@Model.Password"></label>
        <input asp-for="@Model.Password" class="form-control" />
    </div>
    <div class="my-3">
        <label asp-for="@Model.CreatedAt"></label>
        <input asp-for="@Model.CreatedAt" class="form-control" />
    </div>
    <button type="submit" class="btn btn-outline-success">Register</button>
</form>

Views/Users/read.cshtml
@model IEnumerable<User>

@{
    ViewData["Title"] = "read";
}
@if (Model == null)
{
    <p>No data available.</p>
}
else
{

<table class="table">
    <thead>
        <tr>
            <td>
                @Html.DisplayNameFor(model => model.Name)
            </td>
            
            <td>
                @Html.DisplayNameFor(model => model.CreatedAt)
            </td>
            <td>
                @Html.DisplayNameFor(model => model.IsActive)
            </td>
        </tr>
    </thead>
    <tbody>
        @{
            foreach (var item in Model)
            {
                <tr>
                    <td>
                        @item.Name
                    </td>
                    
                    <td>
                        @item.CreatedAt
                    </td>
                    <td>
                        <a asp-controller="users" asp-action="changeIsActive" asp-route-id="@item.Id" class="btn btn-outline-danger">Active</a>
                    </td>
                    
                    
                </tr>

            }
        }
    </tbody>
</table>
}